[MAIN]
is_local = True
provider_name = ollama
# Available providers: ollama, server, openai, lm-studio, huggingface, google, deepseek, deepseek-api, together, dsk_deepseek, openrouter
# For deepseek-api provider, set is_local = False and add DEEPSEEK-API_API_KEY to your .env file
provider_model = deepseek-r1:14b
provider_server_address = 127.0.0.1:11434
agent_name = Name_of_your_AI
recover_last_session = False
save_session = False
speak = False
listen = False
work_dir =  /Users/mlg/Documents/workspace_for_agenticseek
jarvis_personality = False
languages = en
[BROWSER]
headless_browser = True
stealth_mode = False